import turtle

george = turtle.Turtle()
george.width(5)
george.hideturtle()
george.speed(0)

def drawMazeSection(t):
  for i in range(2):
    t.penup()
    t.forward(28)
    t.pendown()
    t.forward(252)
    t.right(90)
    t.forward(140)
    t.right(90)
  t.right(90)
  t.forward(28)
  t.left(90)
  # primera fila
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(56)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(56)
  t.pendown()
  t.forward(56)
  t.penup()
  t.forward(28)
  
  t.right(90)
  t.forward(28)
  t.right(90)
  #segunda fila
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(84)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(84)
  t.penup()
  t.forward(28)
  #tercera fila
  t.left(90)
  t.forward(28)
  t.left(90)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(56)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(56)
  t.pendown()
  t.forward(56)
  t.penup()
  t.forward(56)
  t.right(90)
  t.forward(28)
  #cuarta fila
  t.right(90)
  t.pendown()
  t.forward(56)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(56)
  t.penup()
  t.forward(56)
  t.pendown()
  t.forward(56)
  t.penup()
  t.forward(28)
  
  t.left(90)
  t.forward(28)
  t.left(90)
  t.forward(28)
  t.left(90)
  #primera columna
  t.forward(84)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.right(90)
  t.forward(28)
  t.right(90)
  #segunda columna
  t.forward(56)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(56)
  t.left(90)
  t.forward(28)
  t.left(90)
  #tercera columna
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(56)
  t.penup()
  
  t.right(90)
  t.forward(28)
  t.right(90)
  # cuarta columna
  t.forward(56)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.left(90)
  t.forward(28)
  t.left(90)
  #quinta columna
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.right(90)
  t.forward(28)
  t.right(90)
  #sexta columna
  t.forward(56)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.left(90)
  t.forward(28)
  t.left(90)
  # septima columna
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(28)
  t.right(90)
  t.forward(28)
  t.right(90)
  # octava columna
  t.forward(28)
  t.pendown()
  t.forward(56)
  t.penup()
  t.forward(56)
  t.left(90)
  t.forward(28)
  t.left(90)
  # novena columna
  t.forward(56)
  t.pendown()
  t.forward(28)
  t.penup()
  t.forward(56)

y = 160
george.color("black")
george.penup()
george.goto(-190, y)
george.pendown()
drawMazeSection(george)